### ISSUE TITLE
Adding to friends

### ISSUE THREAD

**Issue by Neurotoxin001** [funkydude/BadBoy_Levels#10]
```
	local addFriend = ERR_FRIEND_ADDED_S:gsub("%%s", "([^ ]+)")
	local removeFriend = ERR_FRIEND_REMOVED_S:gsub("%%s", "([^ ]+)")
```
Every time I have whisper I see "you added friend" message, even if message was hidden, this is annoying. Can you hide this system message please?

Also you might want to update links to other BadBoy plugins here:
https://www.curseforge.com/wow/addons/bad-boy
They lead to not working domain mods.curse.com
![image](https://user-images.githubusercontent.com/39812401/96360267-3fb12180-1124-11eb-9f76-48308450dd12.png)

**Comment by funkydude** [comment]
You quoted the code that's in place, the evidence that this is already filtered, so I'm not sure what problem you're having.

Have you changed where system messages are printed?
Try providing a screenshot of the problem.

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/96373973-8d577980-1178-11eb-94a2-e679265b82b3.png)
It's on russian but here is translate:
`You added CharacterNick to friend list`
`CharacterNick comes online`
And this is popups every time I get a whisper. When I disabled BadBoy_Levels these popups is gone.

**Comment by funkydude** [comment]
Have you moved where system messages are printed away from chat frame 1?

**Comment by Neurotoxin001** [comment]
No, all chat settings is default

**Comment by funkydude** [comment]
Thanks for the report. Try the new update please.
