### ISSUE TITLE
Not Writing to History

### ISSUE THREAD

**Issue by Wienerbandit** [funkydude/BadBoy_Levels#12]
## Describe the problem

I’ve tried uninstalling and messing around with settings but this does not seem to be writing to the BadBoys_History plugin. 

### What steps will reproduce the problem?

1.  Open Badboy_History in game
2.  
3.

**Comment by funkydude** [comment]
Not a BadBoy_Levels issue.

**Comment by Wienerbandit** [comment]
Badboy_History, then?Sent from my iPadOn May 20, 2023, at 2:26 AM, Funkeh ***@***.***> wrote:﻿
Not a BadBoy_Levels issue.
