### ISSUE TITLE
visible "You don't meet the requirements to whisper me" replies

### ISSUE THREAD

**Issue by awerafd** [funkydude/BadBoy_Levels#14]
## Describe the problem
Hello,
As of recently, I've noticed that when players try to whisper me - their message is filtered (not visible), but the automatic reply from me to them is visible ("You dont meet the requirements...") in the chatbox.

### What version of the addon are you using? (Stating 'latest' is not useful)
10.1.4 (18 Sept 2023)

### Any additional information? (example: WoW language if not English)
I am using 3 of your addons - BadBoy, Badboy_History and  BadBoy_Levels with the following options enabled:
![badboy](https://github.com/funkydude/BadBoy_Levels/assets/147457787/bc05e3ad-c0e3-47f2-8ccd-55930aa5f62b)

I suspect the issue might be related to the "Ällow group" option, as so far I have seen the "You dont meet the requirements..." automatic reply twice after finishing M+ and disbanding the group. The third time was a reply to a person that I have been in a group with a week earlier.

**Comment by funkydude** [comment]
Try with only the badboy addons enabled and see if it still occurs.

**Comment by funkydude** [comment]
No response, closing.
