### ISSUE TITLE
Not blocking

### ISSUE THREAD

**Issue by Manniala** [funkydude/BadBoy_Levels#2]
BadBoy v7.2.51
BadBoy Levels v7.3.0
BadBoy Ignore v7.3.0
BadBoy CCleaner v7.3.7

So i want to use Block ALl Whispers, i dont want any whispers from anyone, i dont know anyone that play, im not interested in say it as it is idiots whisper me after a BG or raid... but its just not blocking anything.

People can still whisper me as if i were not using any addon, i thought the option "Block All Whispers" were no one could whisper me no matter what ?

Also the lvl req dos not work for me either, people calling them self Blízzard a lvl 1 can still whisper me, have gotten spam from him several times to urge me to go to a URL to verify im the owner, and ofc i were the first to do that, because im that stupid, no fuck no, and i have reported him 4 times on the forum, 2 times in a Ticket, and he still after 1 month have hes char, im not sure why they allow a Mage use that name, (btw the I is not a I as such, its a ´on the í.) You might want to put in default to block players with those names.

**Comment by funkydude** [comment]
Sounds like you have another addon interfering. I suggest you try disabling non-badboy addons and see if it works.

**Comment by Manniala** [comment]
Ah did not think about that part :D

It could then be like [https://mods.curse.com/addons/wow/global-ignore-list](url) i use that to have a global ignore list on all chars.
