### ISSUE TITLE
Unexpected GUID requested by an addon:

### ISSUE THREAD

**Issue by mLgz0rn** [funkydude/BadBoy_Levels#4]
After the recent update to wow, I have been getting this error, I got no idea if it's badboy related of if it's elvui, since both shows up as spitting out error's

> 
> Message: BadBoy: Unexpected GUID requested by an addon: Disxo
> Time: 12/09/17 23:17:05
> Count: 2
> Stack: BadBoy: Unexpected GUID requested by an addon: Disxo
> Interface\SharedXML\SharedBasicControls.lua:208: in function ><Interface\SharedXML\SharedBasicControls.lua:207>
> Interface\AddOns\BadBoy\BadBoy.lua:74: in function `BadBoyIsFriendly'
> Interface\AddOns\BadBoy_Levels\BadBoy_Levels.lua:196: in function `filterFunc'
> Interface\AddOns\ElvUI\Modules\chat\chat.lua:1129: in function `ChatFrame_MessageEventHandler'
> Interface\AddOns\ElvUI\Modules\chat\chat.lua:1862: in function 
>
> <Interface\AddOns\ElvUI\Modules\chat\chat.lua:1845
> 
> Locals: <none>

I'm also getting this error from the ccleaner addon

> Message: BadBoy: Unexpected GUID requested by an addon: Culetto-TheVentureCo
> Time: 12/09/17 23:17:05
> Count: 1
> Stack: BadBoy: Unexpected GUID requested by an addon: Culetto-TheVentureCo
> Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
> Interface\AddOns\BadBoy\BadBoy.lua:74: in function <Interface\AddOns\BadBoy\BadBoy.lua:69>
> Interface\AddOns\BadBoy_CCleaner\BadBoy_CCleaner.lua:24: in function `filterFunc'
> Interface\AddOns\ElvUI\Modules\chat\chat.lua:1129: in function `ChatFrame_MessageEventHandler'
> Interface\AddOns\ElvUI\Modules\chat\chat.lua:1862: in function <Interface\AddOns\ElvUI\Modules\chat\chat.lua:1845>
> 
> Locals: <none>

**Comment by funkydude** [comment]
You have some addon breaking the filtering system, passing names to a field that expects GUIDs.

**Comment by mLgz0rn** [comment]
Guess I will need to disable all addons except badboy and enable them one by one? :D
